import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/provider/NextAuthSessionProvider";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata = {
   title: "Coffee Shop",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <NextAuthSessionProvider>
            <body
               className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
               {children}
            </body>
         </NextAuthSessionProvider>
      </html>
   );
}
